Add linting and enforce on CI (#6)
* add lint task

* add gci for import order; add CI task; add pre-commit hook

* build should fail

* move lint task to ubuntu only

* use non-deprecated command

* fix lint

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -2,6 +2,26 @@ name: CI
 on:
   push:
 jobs:
+  lint:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-go@v4
+        with:
+          go-version: '>=1.20.0'
+      - name: Lint
+        run: |
+          go install golang.org/x/tools/cmd/goimports@latest
+          go install github.com/daixiang0/gci@latest
+
+          goimports -w .
+          gci write .
+
+          if [ -n "$(git status --porcelain)" ]; then
+            echo '🧼 To fix this check, install required tooling and run "goimports -w . && gci write .;"'
+            git status # Show the files that failed to pass the check.
+            exit 1
+          fi
   test:
     strategy:
       fail-fast: false
@@ -13,4 +33,5 @@ jobs:
       - uses: actions/setup-go@v4
         with:
           go-version: '>=1.20.0'
-      - run: go test -v ./... -cover
+      - name: Test
+        run: go test -v ./... -cover
